---
- name: Install Docker dependencies
  apt:
    force_apt_get: true
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg

- name: Add Docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/debian stretch stable
    state: present

- name: Install Docker
  apt:
    force_apt_get: true
    name:
      - docker-ce

- name: Install pip
  apt:
    force_apt_get: true
    name:
      - python-pip

- name: Install docker for python
  pip:
    name:
      - docker

- name: Run MySQL
  docker_container:
    name: mysql-server
    image: mysql/mysql-server:5.7
    state: started
    restart: yes
    ports:
      - 3306:3306
    env:
      MYSQL_ROOT_PASSWORD: "{{ database_root_password }}"
      MYSQL_DATABASE: "{{ database_name }}"
      MYSQL_USER: "{{ database_user }}"
      MYSQL_PASSWORD: "{{ database_user_password }}"
