---
- name: Run MySQL
  docker_container:
    name: mysql-server
    image: mysql/mysql-server:5.7
    state: started
    restart: yes
    ports:
      - 3306:3306
    env:
      MYSQL_ROOT_PASSWORD: "{{ database_root_password }}"
      MYSQL_DATABASE: "{{ database_name }}"
      MYSQL_USER: "{{ database_user }}"
      MYSQL_PASSWORD: "{{ database_user_password }}"
