---
- name: Run Application
  docker_container:
    name: application
    image: ocpu/microblog
    state: started
    restart: yes
    ports:
      - 8000:5000
    env:
      SECRET_KEY: my-secret-key
      DATABASE_URL: "mysql+pymysql://microblog:passwd@{{ groups.database[0] }}:3306/microblog"
    