---
- name: Install Docker dependencies
  apt:
    force_apt_get: true
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg

- name: Add Docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/debian stretch stable
    state: present

- name: Install Docker
  apt:
    force_apt_get: true
    name:
      - docker-ce

- name: Install pip
  apt:
    force_apt_get: true
    name:
      - python-pip

- name: Install docker for python
  pip:
    name:
      - docker

- name: Run Application
  docker_container:
    name: application
    image: ocpu/microblog
    state: started
    restart: yes
    ports:
      - 8000:5000
    env:
      SECRET_KEY: my-secret-key
      DATABASE_URL: "mysql+pymysql://microblog:passwd@{{ groups.database[0] }}:3306/microblog"
    